apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo
  labels:
    app: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
      - name: demo
        image: sea4choi/demo:latest
        resources:
          requests:
            memory: "512Mi"
            cpu: "1024m"
          limits:
            memory: "512Mi"
            cpu: "1024m"
        ports:
        - containerPort: 8000
        livenessProbe:
          httpGet: # http의 GET 요청으로 사용
            path: /health # GET으로 사용할 path
            port: 8000 # Port 정보
            httpHeaders:
            - name: Custom-Header
              value: Awesome
          initialDelaySeconds: 3
          periodSeconds: 3