logging:
  level:
    root: info
    com:
      zaxxer:
        hikari: debug
spring:
  application:
    name : demo
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: password
    url: jdbc:mysql://mysql:3306/demo
    hikari:
      maximum-pool-size: 2
      minimum-idle: 1
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        highlight_sql: true
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

server:
  port: 8080
